sudo: required

language: go

go:
  - 1.10.1

services:
  - docker

cache:
  directories:
    - vendor/

env:
  global:
    - CGO_ENABLED=0
    - GOBUILD="linux-amd64 windows-amd64 darwin-amd64"

script:
  - GOBUILD=${GOBUILD} make -j dist
  - ls -la build

after_success:
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then make -j docker TAG=pr-$TRAVIS_PULL_REQUEST COMMIT=$TRAVIS_COMMIT; fi
  - if [[ "$TRAVIS_TAG" =~ ^v.*$ ]]; then make -j docker TAG=$TRAVIS_TAG COMMIT=$TRAVIS_COMMIT; fi
  - if [[ "$BRANCH" == "master" ]]; then make -j docker TAG=latest COMMIT=$TRAVIS_COMMIT; fi

deploy:
  provider: releases
  api_key:
    secure: wppJrnbyESDdsWoQ7Nq8M5o3cKIa9oU/EhCdNDgFZ3smgJI4gMSNYz3Th4atvtMr4VJxAyuQznBEWQ+ZRQIvTah+5kZ9gH70ccv9ZqdjNz3BBUcigimPu1BDDvdOCuBc2kqd2RXVtrQ2LlwW7iNM77ziQFMD6YvHGPqeTXOexagh8jFcGum9W+v7O59in5agBO/mP0Bi1+JQg5OLrmhT58d8OS7J9Z22jNhTrOsbQzPJhmE6Da/l8XAJGNRkYFwzySI3hGHe+MepyQj5bD2LPI0cFmMLqqb7c+B6X+JYWokArIpNL1a7bWyrOO0ZuuHRO58ii3uwWnzPsb9XTVHVCzX9VsJT2B3GIRxWrgpzlakuCLD7YIzXzsgCfPjQGGQPiCFDVfhx++bcpMedh3SJ2FezazQlEH4TKTrSJUZProIzwLHbZBRaOtnoinBgC7R2iskf652O33/aQw5/cEWmzxc0iEOyGwhet0xnNrg86vzYb/a1JiGVWJ0wJctt2Diz3k0OjZEIY7sJ/hCplsUVnh/Y7ky234MYHFQFqrDBWBzxbZYvP+hYfQ3u2v7eS4kyA3qKad3lPD1DgwAt67DiB+TpDNber+N812mpKUsJl1pTVljpEoSpGZOhOf/6xwE2UXfnqtp3XkAam/NOec1HddR8pSLEu2rzDccpPent/vU=
  file:
    - build/nomad-helper-linux-amd64
    - build/nomad-helper-windows-amd64
    - build/nomad-helper-darwin-amd64
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: seatgeek/nomad-helper
